apiVersion: v1
kind: Service
metadata:
  name: mini-java-app-service
  namespace: mini-java-app
  labels:
    app: mini-java-app
    managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: mini-java-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
