apiVersion: v1
kind: Service
metadata:
  name: mbasic-service
  namespace: mbasic
  labels:
    app: mbasic
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: mbasic
